# Generate a file containing the word "Hello"
genrule(
    name = "gen_hello",
    cmd = "echo 'Hello' > $@",
    outs = ["hello.txt"],
)

# Copy the file generated by the other genrule to a temporary file called
# tmp.txt, which inherits the same permissions.
#
# Then attempt to modify the file by appending the word "World". This will fail
# because we cannot write to the file. And we cannot write to the file because
# the :gen_hello rule set it to read-only.
genrule(
    name = "add_world",
    srcs = [":hello.txt"],
    cmd = """
cp $(location hello.txt) tmp.txt

echo "\nCan't append, file has these permissions:"
ls -la tmp.txt

echo 'World' >> tmp.txt

cp tmp.txt $@
""",
    outs = ["hello_world.txt"],
)

# Fixes the broken genrule by making tmp.txt writable.
genrule(
    name = "add_world_fixed",
    srcs = [":hello.txt"],
    cmd = """
cp $(location hello.txt) tmp.txt

chmod 666 tmp.txt

echo 'World' >> tmp.txt
cp tmp.txt $@
""",
    outs = ["hello_world_fixed.txt"],
)
